apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: brenda-demo-backend
spec:
  selector:
    matchLabels:
      app: brenda-demo-backend
  template:
    metadata:
      labels:
        app: brenda-demo-backend
    spec:
      containers:
      - name: frontend
        image: beltranalex928/workwaves-backend:latest
        imagePullPolicy: Always
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                key: url          
                name: workwaves-mongo
        ports:
        - containerPort: 2000
