apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
spec:
  selector:
    matchLabels:
      app: resume
  replicas: 3
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - name: resume
        image: beltranalex928/resume:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
