apiVersion: apps/v1 
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 3
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: node
        image: beltranalex928/website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
