apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - https-alexbeltran.dev
    secretName: alexbeltran.dev
  rules:
  - host: https-alexbeltran.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: website
            port:
              number: 80